""" wsg_1.py script """

#!/usr/bin/env python
#import os

import datetime
import pprint

DEFAULT = "No Value Set"

BODY = """<html>
<head>
<title>Lab 3 - WSGI experiments</title>
</head>
<body>
<p>Hey there, this page has been generated by {software}, running at {path}</p>
<p>Today is {month} {date}, {year}.</p>
<p>This page was requested by IP Address {client_ip}</p>
</body>
</html>"""

def application(environ, start_response):
    """ application """
    pprint.pprint(environ)

    response_body = BODY.format(
        software=environ.get('SERVER_SOFTWARE', DEFAULT),
        path=environ.get('PATH_INFO', DEFAULT),
        month=datetime.datetime.now().strftime('%B'),
        date=datetime.datetime.now().day,
        year=datetime.datetime.now().year,
        client_ip=environ.get('REMOTE_ADDR', DEFAULT),
    )
    status = '200 OK'

    response_headers = [('Content-Type', 'text/html'),
                        ('Content-Length', str(len(response_body)))]
    start_response(status, response_headers)

    return [response_body.encode('utf-8')]

if __name__ == '__main__':
    from wsgiref.simple_server import make_server
    SRV = make_server('localhost', 8080, application)
    SRV.serve_forever()
    